[profile.default]

[forge]
src = "solidity/contracts"
test = "solidity/tests"
out = ""solidity/out"
libs = ["node_modules"]

[scripts]
src = "solidity/scripts"





# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
